version: '3.8'

services:
  web:
    build: .
    container_name: inbound-carrier-sales-api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      - DATABASE_NAME=${DATABASE_NAME:-happyrobot}
      - LOADS_COLLECTION_NAME=${LOADS_COLLECTION_NAME:-loads}
      - CARRIERS_CALLS_COLLECTION_NAME=${CARRIERS_CALLS_COLLECTION_NAME:-carriers_calls}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - FMCSA_API_KEY=${FMCSA_API_KEY}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/venv  # Exclude venv from volume mount
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MongoDB for local development
  # mongodb:
  #   image: mongo:7
  #   container_name: inbound-carrier-mongo
  #   restart: unless-stopped
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: password
  #   volumes:
  #     - mongodb_data:/data/db

# volumes:
#   mongodb_data: